### ISSUE TITLE
How can i add new line to sent text?

### ISSUE THREAD

**Issue by direrFlood** [nonrice/discord-auto-message#12]
Hey,
I have long shouting message that i need to send every 1 hours. It has alot of new lines. How can I send ,a message with new lines?
for example this text message:
```
"
Hey,
I am using discord auto message
look there is new line
"
```
Maybe add text file input, and make it get the text until EOF. I am very bad at programming. but i understand the logic behind it.

**Comment by nonrice** [comment]
When you want a newline, type `\n` into your message

**Comment by direrFlood** [comment]
exactly what i did without telling me, when used this the message was sent like this:
```
"
Hey, \nI am using discord auto message \n look there is new line
"

```

**Comment by direrFlood** [comment]
pull request #13
