### ISSUE TITLE
Can I have help?

### ISSUE THREAD

**Issue by SniperXKiller** [nonrice/discord-auto-message#2]
Hello, I have tried to use your auto typer code, but there are a few things that I need help with.
First, every time I run it, it says:

An error was found inside the info file (possibly your first time using?), reconfiguring is required.
Refer to Google if some of these parameters are unfamiliar. It should yield more than usable results.
User agent: 
Discord token: 
Discord channel URL: 
Discord channel ID: 
Messages will be sent to .
Message to send: 
Amount of messages: 

How do you get the User agent, and channel ID?
- SXK

**Comment by SniperXKiller** [comment]
Actually, after doing a lot of research, I figured all of this out

**Comment by nonrice** [comment]
Simply google search "what is my user agent" and it will tell you.
