### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by zenn66** [nonrice/discord-auto-message#5]
bot closes every time i try to open it with python

**Comment by nonrice** [comment]
That's not good. Can you send a screenshot of everything that happened?

**Comment by zenn66** [comment]
Hey man I have another issue now I fixed the closing part but now when I
try to configure the bot it stops working like it doesn't respond anymore
no options or anything

**Comment by nonrice** [comment]
May you send a screenshot of the terminal after the issue occurs? You can use type in dummy values in place of your actual information. It is hard to help when I do not know how you are running into the issue.

**Comment by zenn66** [comment]
[image: image.png]
the bot stops responding after this part

**Comment by nonrice** [comment]
<img width="566" alt="Screen Shot 2022-04-23 at 10 39 50 PM" src="https://user-images.githubusercontent.com/17582488/165187570-6004fb18-2d6a-4406-8285-5c84cc09adbe.png">
?

**Comment by nonrice** [comment]
I cannot see the image. Can you try sending it again? You can drag and drop the image into the reply section.

**Comment by zenn66** [comment]
[image: Screenshot 2022-04-25 185753.png]

**Comment by nonrice** [comment]
Hmm, this is strange. I still cannot see the image. Can you instead copy and paste the contents of your prompt?

**Comment by zenn66** [comment]
***@***.*** MINGW32 ~
$ cd ./discord-auto-message/discord_bot/

***@***.*** MINGW32 ~/discord-auto-message/discord_bot (main)
$  python3 bot.py
An error was found inside the user information file. Run the script with
the 'Sepython3 bot.py --setall') to reconfigure.

***@***.*** MINGW32 ~/discord-auto-message/discord_bot (main)
$ ls
bot.py  info.txt

***@***.*** MINGW32 ~/discord-auto-message/discord_bot (main)
$ python3 bot.py
An error was found inside the user information file. Run the script with
the 'Sepython3 bot.py --setall') to reconfigure.

***@***.*** MINGW32 ~/discord-auto-message/discord_bot (main)
$ python3 bot.py --setall
Configure bot? (y/n) y
(then nothing happens)

**Comment by nonrice** [comment]
Try running the set all command, and type in y. Then when the program does not print anything, type 4 random things, pressing `enter` after each of them. Check the contents of the `info.txt` file. Does it match what you typed?

**Comment by zenn66** [comment]
No, nothing in the info.txt file is changed or added

**Comment by nonrice** [comment]
Making a wild guess here, but: try doing the same thing in another terminal (e.g. powershell). I've seen some reports of Git Bash not cooperating with Python. They don't match the exact issue you are having, but I still think it'd be worth a try. Let me know how it goes.

**Comment by zenn66** [comment]
Ok I'm using widows PowerShell now, but I need a bit of help configuring
the bot... What is a user agent?

**Comment by nonrice** [comment]
google "what is my user agent" and paste in the result

for user token, there are some youtube tutorials out there. it's pretty simple.

Channel Url is the url of the channel when you are visiting it in browser

Channel id is obtained by right clicking on a channel and pressing "copy id". You need to enable developer mode in discord settings>appearance i believe.

**Comment by zenn66** [comment]
Awesome, thanks!

**Comment by nonrice** [comment]
No problem! Glad you got it working in the end.
