### ISSUE TITLE
Keep Getting Error

### ISSUE THREAD

**Issue by bendoverv5** [nonrice/discord-auto-message#9]
i keep receiving an error when trying the bot, i have tried many different servers. is it probably cuz im running the bot on a rdp or ?

Error Message:

"Received HTTP 401: Unauthorized
Estimated time to complete: 0 minutes.
Iteration 0 complete."

THX

**Comment by nonrice** [comment]
Hi,

I find this error occurs when the provided credentials/other info are incorrect. Are you sure you entered the user token, channel id, and channel channel url correctly? (Make sure that that the user token is pasted in without quotation marks.)

**Comment by bendoverv5** [comment]
yes, i entered wrong token lol thx i got it working now
